### PR TITLE
ETUI-1620 - fix(rxDataTable): removing previous table hover solution

### PR DESCRIPTION
**Pull request by JoseVillarreal**
[ETUI-1620](https://jira.rax.io/browse/ETUI-1620)

related: [UI PR 820](https://github.com/rackerlabs/encore-tq-ui/pull/820)

### CODE REVIEW

**Comment by tomreece** [comment]
@JoseVillarreal should the `cellMouseEnter()` and `cellMouseLeave()` functions be removed. They appear to be unused now after this change.

**Comment by JoseVillarreal** [comment]
Yeah, good call, I'll remove them.

**Comment by tomreece** [comment]
Cool, after that, LGTM.

**Comment by JoseVillarreal** [comment]
Closing to consolidate code

**Pull request closed without merging**
